Translated api/configuration-build.md to Russian
theartkod/docs pull request #10
Opened 2020-04-16 11:11 UTC by icehaunter

2020-04-18 13:27 UTC, DreaMinder requested changes
Есть несколько  замечаний, а так все ок.

2020-04-18 13:27 UTC, DreaMinder commented on ru/api/configuration-build.md
> +**Заметка**: предустановленный набор настроек, указанный в `build.babel.presets` будет применен к обоим сборкам, как клиентской, так и серверной. Цель сборки будет установлена Nuxt соответственно (кл
к об**е**им сборкам*

> Цель сборки будет установлена Nuxt соответственно (клиент/сервер).

непонятно о чем речь без падежа. Может так? 
> фреймворком Nuxt

2020-04-18 13:27 UTC, DreaMinder commented on ru/api/configuration-build.md
> +Этот пример заменяет красивые имена файлов на обычные числа (`nuxt.config.js`):
на числовые идентификаторы*

2020-04-18 13:27 UTC, DreaMinder commented on ru/api/configuration-build.md
> +  useShortDocТип: true
тут нужно откатить на англ версию

2020-04-18 13:27 UTC, DreaMinder commented on ru/api/configuration-build.md
> +Вы можете задать значением `minimizer` массив плагинов, или присвоить `minimize` значение `false`, что бы отключить
чтобы*

2020-04-18 13:27 UTC, DreaMinder commented on ru/api/configuration-build.md
> +Ваши настройки плагинов будут слиты с настройками по умолчанию (только если вы не используете массив вместо объекта).
слиты... может лучше смешаны?

2020-04-18 18:39 UTC, cogor commented on ru/api/configuration-build.md
> +Ваши настройки плагинов будут слиты с настройками по умолчанию (только если вы не используете массив вместо объекта).
Как по мне, "объединены" звучит лучше

2020-04-18 18:54 UTC, DreaMinder commented on ru/api/configuration-build.md
> +Ваши настройки плагинов будут слиты с настройками по умолчанию (только если вы не используете массив вместо объекта).
о, точно

2020-07-09 21:54 UTC, DreaMinder requested changes

2020-07-09 21:54 UTC, DreaMinder commented on ru/api/configuration-build.md
> +    followSymlinks: false
а как это так? в доке это значение true

```suggestion
    followSymlinks: true
```

2020-07-14 16:06 UTC, icehaunter commented on ru/api/configuration-build.md
> +    followSymlinks: false
Во время ребейзов запутался

2020-07-17 10:00 UTC, DreaMinder approved these changes
Noice

2020-07-17 10:00 UTC, merged