Translated guide/commands.md to Russian
theartkod/docs pull request #12
Opened 2020-04-20 13:52 UTC by cogor

Translated guide/commands.md to Russian

2020-04-22 13:18 UTC, DreaMinder requested changes
Есть пара замечаний, а так все хорошо.

2020-04-22 13:18 UTC, DreaMinder commented on ru/guide/commands.md
> +> Nuxt.js поставляется с набором полезных команд, как для разработки, так и для развертывания.
>  полезных команд, как для разработки

тут вроде без запятой должно быть

2020-04-22 13:18 UTC, DreaMinder commented on ru/guide/commands.md
> +Для развертывания, вместо запуска `nuxt`, вам, возможно, понадобится выполнить сборку раньше или в другом месте. Поэтому, сборка и запуск это разные команды:
раньше -> заранее

2020-04-22 13:18 UTC, DreaMinder commented on ru/guide/commands.md
> +Для возвращения не нулевого кода статуса, если обнаружена ошибка на странице и CI/CD не удалось выполнить развертывание или сборку, вы можете использовать аргумент `--fail-on-error`.
ненулевого*

2020-04-22 13:18 UTC, DreaMinder commented on ru/guide/commands.md
> +Идея SPA очень простая, когда включен режим SPA используя `mode: 'spa'` или флаг `--spa`, и мы запустим сборку, генерация автоматически начнется со сборки. Сгенерированные страницы будут содержать об
Может лучше: 
`Идея SPA очень простая:` (двоеточие)

2020-04-23 09:15 UTC, cogor commented on ru/guide/commands.md
> +> Nuxt.js поставляется с набором полезных команд, как для разработки, так и для развертывания.
Верно

2020-04-23 09:18 UTC, cogor commented on ru/guide/commands.md
> +Идея SPA очень простая, когда включен режим SPA используя `mode: 'spa'` или флаг `--spa`, и мы запустим сборку, генерация автоматически начнется со сборки. Сгенерированные страницы будут содержать об
Заменил на `Идея SPA очень проста:`

2020-04-23 09:19 UTC, merged