ru200706: Translation index.md
theartkod/docs pull request #31
Opened 2020-07-06 09:00 UTC by Domovikx

2020-07-06 09:03 UTC, theartkod requested changes
надо бы в гитигнор добавить директорию с настройками для вскода

2020-07-06 23:39 UTC, DreaMinder requested changes
Есть спорные моменты и замечания.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +название: Введение
```suggestion
title: Введение
```

это же yaml ключи, по ним в макет все подставляться будет, низя переводить.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +описание: "Nuxt - это прогрессивный фреймворк, основанная на Vue.js для создания современных веб-приложений. Он основан на официальных библиотеках Vue.js (vue, vue-router и vuex) и мощных инструмента
```suggestion
description: "Nuxt - это прогрессивный фреймворк, основанный на Vue.js для создания современных веб-приложений. Он основан на официальных библиотеках Vue.js (vue, vue-router и vuex) и мощных инструментах разработки (webpack, Babel и PostCSS)."
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Универсальный по своей природе, он поддерживает различные цели (серверные, бессерверные или статические), а рендеринг на стороне сервера можно переключать.
```suggestion
Универсальный по своей природе, он поддерживает различные платформы (серверные, бессерверные или статические), а рендеринг на стороне сервера можно как включать, так и выключать.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Расширяемый с помощью сильной модульной экосистемы, он позволяет легко подключать конечные точки REST или GraphQL, любимые CMS, CSS-фреймворки и многое другое. Готовая поддержка PWA и AMP - в виде мо
```suggestion
Расширяемый с помощью мощной модульной экосистемы, он позволяет легко подключать конечные точки REST или GraphQL, любимые CMS, CSS-фреймворки и многое другое. Готовая поддержка PWA и AMP - требует лишь установить модуль в ваш проект Nuxt.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +- Готовые HTTP/2 заголовки
```suggestion
- Поддержка HTTP/2 заголовков
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +- Пакетирование и минимизация вашего JS & CSS
```suggestion
- Сборка и минимизация вашего JS & CSS
```

Спорно, но "пакетирование" режет слух.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Для создания богатой разработки веб-приложений, Nuxt.js включает в себя следующее:
```suggestion
Для обеспечения всеохватывающей разработки веб-приложений, Nuxt.js включает в себя следующее:
```
Спорно, но тут точно не "богатая разработка".

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +## Схема
```suggestion
## Схема

```

Походу удалилась пустая строка, без нее разметка может глючить.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Эта схема показывает, что вызывается Nuxt.js, когда вызывается сервер или когда пользователь перемещается по приложению через nuxt-ссылку `<nuxt-link>`:
```suggestion
Эта схема показывает, что вызывает Nuxt.js при запросе на сервер или когда пользователь перемещается по приложению через nuxt-ссылку `<nuxt-link>`:
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +При запуске `nuxt` запускается сервер разработки с горячей перезагрузкой и [Vue Server Renderer](https://ssr.vuejs.org/ru/), настроенный на автоматическую серверную визуализацию вашего приложения.
```suggestion
При запуске `nuxt` запускается сервер разработки с горячей перезагрузкой и [Vue Server Renderer](https://ssr.vuejs.org/ru/), настроенный на автоматический серверный рендеринг вашего приложения.
```

Слово "Визуализация" как-то неприменимо к ренжерингу хтмла.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Если по какой-либо причине вы предпочитаете не использовать рендеринг на стороне сервера (SSR) или вам нужен статический хостинг для ваших приложений, вы можете использовать режим SPA с помощью режим
```suggestion
Если по какой-либо причине вы предпочитаете не использовать рендеринг на стороне сервера (SSR) или вам нужен статический хостинг для ваших приложений, вы можете использовать режим SPA с помощью команды `nuxt --spa`. В сочетании с командой `generate`, он дает вам мощный механизм развертывания SPA без необходимости использования среды выполнения Node.js или какой-либо специальной обработки сервером.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Если у вас уже есть сервер, вы можете подключить Nuxt.js, используя его в качестве промежуточного программного обеспечения. Нет никаких ограничений при использовании Nuxt.js для разработки ваших унив
```suggestion
Если у вас уже есть сервер, вы можете подключить Nuxt.js, используя его в качестве промежуточного программного обеспечения. Нет никаких ограничений при использовании Nuxt.js для разработки ваших универсальных веб-приложений. [См. Руководство](https://ru.nuxtjs.org/api/nuxt/) по использованию Nuxt.js.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Большое новшество в Nuxt.js - это команда экспорта `nuxt build && nuxt export` для Nuxt >= v2.13 или команда создания `nuxt generate` для Nuxt <= v2.12.
```suggestion
Большое новшество в Nuxt.js - это команда экспорта `nuxt build && nuxt export` для Nuxt >= v2.13 или команда `nuxt generate` для Nuxt <= v2.12.
```

Не понимаю, почему создания...

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Будет сгенерировано, как:
Честно говоря я слаб в грамматике, но тут точно нужна запятая?

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Лучший пример этого сайта. Он создается и размещается на [Netlify](https://www.netlify.com), смотри наш [исходный код](https://github.com/nuxt/nuxtjs.org) или [как развернуть Nuxt.js в Netlify](https
```suggestion
Лучший пример - этот сайт. Он генерируется статически и размещается на [Netlify](https://www.netlify.com), смотри наш [исходный код](https://github.com/nuxt/nuxtjs.org) или [как развернуть Nuxt.js в Netlify](https://vueschool.io/lessons/how-to-deploy-nuxtjs-to-netlify?friend=nuxt) из Vue School.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Мы не хотим вручную генерировать приложение каждый раз, когда обновляем хранилище документов, оно вызывает перехват Netlify, который:
```suggestion
Мы не хотим вручную генерировать приложение каждый раз, когда обновляем репозиторий документации, оно вызывает команду Netlify, которая:
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +4. Обслуживает каталог `dist`
```suggestion
4. Отдает каталог `dist` в публичный доступ
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Новый полностью статический модуль, который доступен начиная с v2.13, генерирует ваши html и статические активы во время сборки, что означает, что все уже сгенерировано, и, следовательно, он не тольк
```suggestion
Новый модуль полной статической генерации, который доступен начиная с v2.13, генерирует ваши html и статические файлы во время сборки, что означает, что все уже сгенерировано, и, следовательно, он не только отлично подходит для SEO, но также может бесплатно размещаться на любом статическом хостинге.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Nuxt v2.13 также поставляется с установленным сканером, который будет сканировать ваши теги ссылок и генерировать ваши динамические маршруты на основе этих ссылок, что означает, что вам больше не нуж
```suggestion
Nuxt v2.13 также поставляется с установленным сканером, который будет сканировать ваши теги ссылок и генерировать ваши динамические маршруты на основе этих ссылок, что означает, что вам больше не нужно вручную генерировать ваши динамические маршруты.
```

Походу у них в англ. доке ошибка.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Статическая цель работает, сохраняя вызовы вашего API в файлах payload.js в статической папке. Эти полезные данные затем кэшируются для повышения производительности и поддержки в автономном режиме, и
```suggestion
Статический режим работает, сохраняя вызовы вашего API в файлах payload.js в статической папке. Эти данные затем кэшируются для повышения производительности и поддержки работы в автономном режиме, и поскольку ваш API больше не вызывается при навигации на стороне клиента (при вызове с использованием asyncData и fetch), это также означает, что вам не нужно открывать свой API для публичного доступа.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Когда ваш сайт генерируется, ваш html генерируется со всем его содержимым, и при навигации на стороне клиента эти страницы восстанавливаются с использованием файлов полезной нагрузки (payload files)
```suggestion
Когда ваш сайт генерируется, ваш html генерируется со всем его содержимым, и при навигации на стороне клиента эти страницы восстанавливаются с использованием файлов данных (payload files). Отделяя код от контента, вы можете легко сгенерировать ваш контент без необходимости пересобирать весь ваш сайт. Это означает, что после того, как ваш сайт создан, и вы хотите изменить только свой контент, вы можете просто вызвать `nuxt export`, который будет перегенерировать только ваш контент. Поскольку контент не должен проходить через webpack, регенерация контента происходит быстрее.
```

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Когда ваш сайт генерируется, ваш html генерируется со всем его содержимым, и при навигации на стороне клиента эти страницы восстанавливаются с использованием файлов полезной нагрузки (payload files)
укоротил немного последнее бесконечное предложение.

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +  target: "static",
притиер сам поправил? или это ты?

2020-07-06 23:39 UTC, DreaMinder commented on ru/guide/index.md
> +Для получения более подробной информации смотри [как развернуть на Netlify?](https://ru.nuxtjs.org/faq/netlify-deployment/)
```suggestion
Для получения более подробной информации смотрите [как развернуть на Netlify?](https://ru.nuxtjs.org/faq/netlify-deployment/)
```

2020-07-08 06:24 UTC, Domovikx commented on ru/guide/index.md
> +- [Vue Server Renderer](https://ssr.vuejs.org/ru/) ( исключено при использовании [`mode: 'spa'`](/api/configuration-mode))
Поправить эту ссылку, моде спа

2020-07-08 07:01 UTC, Domovikx commented on ru/guide/index.md
> +  target: "static",
Тут вообще преттиер у меня так ставит, синтаксически тут ошибки нет, включая запятую в конце... Сейчас сделаю красиво. )

2020-07-08 10:39 UTC, DreaMinder requested changes
Еще немного

2020-07-08 10:39 UTC, DreaMinder commented on ru/guide/index.md
> +Статическая режим работает, сохраняя вызовы вашего API в файлах payload.js в статической папке. Эти данные затем кэшируются для повышения производительности и поддержки работы в автономном режиме, и
```suggestion
Статический режим работает, сохраняя вызовы вашего API в файлах payload.js в статической папке. Эти данные затем кэшируются для повышения производительности и поддержки работы в автономном режиме, и поскольку ваш API больше не вызывается при навигации на стороне клиента (при вызове с использованием asyncData и fetch), это также означает, что вам не нужно открывать свой API для публичного доступа.
```

2020-07-08 10:43 UTC, DreaMinder commented
@theartkod 
> надо бы в гитигнор добавить директорию с настройками для вскода

давай выпилим его перед финальным мерджем

2020-07-08 10:44 UTC, DreaMinder approved these changes

2020-07-08 18:14 UTC, merged