Update routing.md
theartkod/docs pull request #32
Opened 2020-07-06 13:53 UTC by merzavko

2020-07-06 14:17 UTC, cogor commented on ru/guide/routing.md
> +  <nuxt-link to="/">Домашння страница</nuxt-link>
```suggestion
  <nuxt-link to="/">Домашняя страница</nuxt-link>
```

2020-07-06 14:17 UTC, cogor commented on ru/guide/routing.md
> +##  Простые пути
```suggestion
## Простые пути
```

2020-07-06 14:17 UTC, cogor commented on ru/guide/routing.md
> +Автоматически сгенерирует:
```suggestion
будет сгенерировано в:
```

2020-07-06 14:17 UTC, cogor commented on ru/guide/routing.md
> +Автоматически сгенерирует:
```suggestion
будет сгенерировано в:
```

2020-07-06 22:48 UTC, DreaMinder requested changes
Все круто кроме пары моментов.

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +**Внимание:** Если вы используете Nuxt >= v2.13 и у вас есть страницы которые не имеют ссылок, как скрытые страницы, и вы хотите сгенерировать и их тоже - вы можете использовать свойство `generate.ro
```suggestion
**Внимание:** Если вы используете Nuxt >= v2.13 и у вас есть страницы на которые нет ссылок, как скрытые страницы, и вы хотите сгенерировать и их тоже - вы можете использовать свойство `generate.routes`. 
```

в этом контексте that have no links скорей переводится как "которые не имеют связей", т.к. речь вообще о том, что еси на страницу никто не ссылается, краулер ее не найдет.


Еще "как скрытые страницы" чуть слух режет, может в скобки засунуть?

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +**Внимание:** При использовании Nuxt <= v2.12 динамические маршруты игнорируются командой `generate`.
```suggestion
**Внимание:** При использовании Nuxt <= v2.12 команда `generate` игнорирует динамические маршруты.
```

Спорный момент, мне показалось так лучше, ближе к делу.

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +Для отображения именованных представлений вы можете использовать компоненты `<nuxt name="top"/>` или `<nuxt-child name="top"/>` в ваших шаблонах/страницах. Чтобы указать именованное представление стр
```suggestion
Для отображения именованных представлений вы можете использовать компоненты `<nuxt name="top"/>` или `<nuxt-child name="top"/>` в ваших шаблонах/страницах. Чтобы указать именованное представление страницы, нужно расширить конфигурацию маршрутизатора в файле `nuxt.config.js`:
```

Сначала вы, потом мы - у нас так не говорят вроде. И насчет запятой не уверен.

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +Вы также можете включить SPA fallbacks для динамических маршрутов. Nuxt.js выведет дополнительный файл, такой же как `index.html`, который будет использоватся в `mode: 'spa'`. Большинство сервисов ст
```suggestion
Вы также можете включить SPA fallbacks для динамических маршрутов. Nuxt.js выведет дополнительный файл, такой же как `index.html`, который будет использоватся в `mode: 'spa'`. Большинство сервисов статического хостинга могут быть настроены на использование шаблона SPA, если ни один файл не подошел. Он не будет содержать в себе `head` или какой-либо HTML, но он все равно будет запускаться и загружать данные с API.
```

Думаю resolve относилось к файлу, а не к апи. "Разрешать" резало слух, но "запускаться" не намного лучше.

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +    fallback: true, // if you want to use '404.html' вместо стандартного '200.html'
```suggestion
    fallback: true, // если хотите использовать '404.html' вместо стандартного '200.html'
```

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +Вы можете получить доступ к текущим параметрам маршрута на своих локальных страницах или компонентах ссылаясь на `this.$route.params.{parameterName}`. Например, если у вас была динамическая страница
```suggestion
Вы можете получить доступ к текущим параметрам маршрута на своих локальных страницах или компонентах ссылаясь на `this.$route.params.{parameterName}`. Например, если у вас была динамическая страница пользователей (`users\_id.vue`) и вы хотели получить доступ к параметру `id` для загрузки информации о пользователе, доступ к переменной можно получить таким способом: `this.$route.params.id`.
```
Выглядело чужеродно, но чем заменить не придумал, потому удалил.

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +#### Имплементация для GitHub Pages и Netlify
обычно у нас пишут "реализация"... но можно и так

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +<b>Информация:</b> Nuxt.js навзание перехода по умолчанию: `"страница"`.
```suggestion
<b>Информация:</b> Nuxt.js название перехода по умолчанию: `"page"`.
```

очепятка и непереводимый ключ

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +В качестве первого аргумента middleware получает [the context](/api/context) :
```suggestion
В качестве первого аргумента middleware получает [context](/api/context) :
```

2020-07-06 22:48 UTC, DreaMinder commented on ru/guide/routing.md
> +В универсальном режиме, middlewares будет вызыватся на стороне сервера один раз (при первом запросе к приложению Nuxt или при обновлении страницы) и на стороне клиента при переходе к дальнейшим маршр
```suggestion
В универсальном режиме, middleware будет вызыватся на стороне сервера один раз (при первом запросе к приложению Nuxt или при обновлении страницы) и на стороне клиента при переходе к дальнейшим маршрутам. При статическом генерировании страниц middleware будет вызываться один раз во время сборки вместо вызовов на стороне сервера. В режиме SPA, будет вызываться на стороне клиента при первом запросе и при переходе к дальнейшим маршрутам.
```

2020-07-07 08:22 UTC, DreaMinder approved these changes
Noice.

2020-07-07 08:23 UTC, merged