Translate ru/guide/modules.md to Russian
theartkod/docs pull request #39
Opened 2020-07-16 18:22 UTC by icehaunter

Closes #18

2020-07-17 10:33 UTC, DreaMinder requested changes
Что бы - это пишется когда "что бы такого сделать".
Чтобы - это когда объясняется "для чего".

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +- Часто сталкиваетесь с короткими сроками, и у вас нет времени залезать в дебри каждой новой библиотки или интеграции
```suggestion
- Часто сталкиваетесь со сжатыми сроками, и у вас нет времени залезать в дебри каждой новой библиотки или интеграции
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +- Устали разбираться с критическими изменениями в каждой библиотеке и хотите что бы всё **просто работало™**.
```suggestion
- Устали разбираться с критическими изменениями в каждой библиотеке и хотите чтобы всё **просто работало™**.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Это объект, который передаётся пользователем при настройке массива `modules`. Мы можем его использовать, что бы настраивать поведение модуля.
```suggestion
Это объект, который передаётся пользователем при настройке массива `modules`. Мы можем его использовать, чтобы настраивать поведение модуля.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Вы можете получить прямой доступ к настройкам Nuxt с помощью этой ссылки. Там находится всё содержимое пользовательского `nuxt.config.js` с заполненными полями по-умолчанию. Они могут быть использова
```suggestion
Вы можете получить прямой доступ к настройкам Nuxt с помощью этой ссылки. Там находится всё содержимое пользовательского `nuxt.config.js` с заполненными полями по-умолчанию. Они могут быть использованы, чтобы пользоваться одними настройками в нескольких модулях.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Эта строка **необходима**, если вы публикуете модуль как npm-пакет. Внутри Nuxt использует метаданные, что бы лучше работать с вашим пакетом.
```suggestion
Эта строка **необходима**, если вы публикуете модуль как npm-пакет. Внутри Nuxt использует метаданные, чтобы лучше работать с вашим пакетом.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +## Распространённые отрывки
```suggestion
## Распространённые куски кода
```
по-моему, так понятей

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +      // Nuxt подменит `options.ua` на `123`при копировании плагина в проект
```suggestion
      // Nuxt подменит `options.ua` на `123` при копировании плагина в проект
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Если ваш модуль предоставляет CSS-библиотеку, то удостоверьтесь, что вы проверили, не добавил ли уже пользователь ту же библиотеку что бы избежать дубликатов, а так же добавьте **опцию, которая отклю
```suggestion
Если ваш модуль предоставляет CSS-библиотеку, то удостоверьтесь, что вы проверили, не добавил ли уже пользователь ту же библиотеку чтобы избежать дубликатов, а так же добавьте **опцию, которая отключит** CSS-библиотеку в модуле.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Мы можем регистрировать плагины для webpack, что бы добавлять ресурсы в процессе сборки.
```suggestion
Мы можем регистрировать плагины для webpack, чтобы добавлять ресурсы в процессе сборки.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Вашему модулю может потребоваться делать какие-то действия только при каких-то условиях, а не просто во время инициализации Nuxt. Мы можем использовать мощную систему хуков Nuxt.js что бы реагировать
```suggestion
Вашему модулю может потребоваться делать какие-то действия только при каких-то условиях, а не просто во время инициализации Nuxt. Мы можем использовать мощную систему хуков Nuxt.js чтобы реагировать на какие-либо события (основано на [Hable](https://github.com/jsless/hable)).
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Затем, обратите внимание, что `NuxtCommand.run()` используется для указания настроек и поведения команды. Опции задаются в параметре `options`; они будут разобраны библиотекой [`minimist`](https://gi
```suggestion
Затем, обратите внимание, что `NuxtCommand.run()` используется для указания настроек и поведения команды. Опции задаются в параметре `options`; они будут разобраны библиотекой [`minimist`](https://github.com/substack/minimist). После того, как аргументы функции были разобраны, функция `run()` вызывается с экземпляром `NuxtCommand` в качестве первого параметра.
```

2020-07-17 10:33 UTC, DreaMinder commented on ru/guide/modules.md
> +Чтобы ваша команда была доступна в Nuxt CLI, добавьте её в секцию `bin` вашего `package.json`, используя соглашение `nuxt-module` , согласно которому `module` согласуется с названием вашего npm-пакет
```suggestion
Чтобы ваша команда была доступна в Nuxt CLI, добавьте её в секцию `bin` вашего `package.json`, используя соглашение `nuxt-module` , согласно которому `module` согласуется с названием вашего npm-пакета. Используя этот файл в качестве входной точки, вы можете использовать `argv` чтобы разобрать "подкоманды" для вашей команды, если вы этого захотите.
```

2020-07-17 17:14 UTC, icehaunter commented on ru/guide/modules.md
> +## Распространённые отрывки
Может быть "отрывки кода"? Мне немного режет слух "куски"

2020-07-17 17:19 UTC, DreaMinder commented on ru/guide/modules.md
> +## Распространённые отрывки
@icehaunter OK, согласен, давай "отрывки"

2020-07-18 20:39 UTC, DreaMinder approved these changes
Найс, спасибо.

2020-07-18 20:40 UTC, merged