Translated api/components-client-only.md
theartkod/docs pull request #4
Opened 2020-04-14 10:45 UTC by icehaunter

2020-04-14 20:37 UTC, DreaMinder requested changes
Пара опечаток и одна формулировка под вопросом.

2020-04-14 20:37 UTC, DreaMinder commented on ru/api/components-client-only.md
> +description: Отрисовка компонента только на стороне клиента, при этом отображая заглушку на стороне сервера.
Немного режет глаз "отображать на сервере", может лучше так?
`Отрисовка компонента только на стороне клиента, при этом отрисовывая заглушку на стороне сервера.`

2020-04-14 20:37 UTC, DreaMinder commented on ru/api/components-client-only.md
> +      <!-- тот компонент будет отрисован только на стороне клиента -->
этот*

2020-04-14 20:37 UTC, DreaMinder commented on ru/api/components-client-only.md
> +Этот компонент импорттирован из [egoist/vue-client-only](https://github.com/egoist/vue-client-only). Спасибо, [@egoist](https://github.com/egoist)!
импортирован*

2020-04-14 21:13 UTC, DreaMinder commented on ru/api/components-client-only.md
> +> Этот компонент используется для того, что бы целенаправленно отрисовать его дочерний компонент только на клиентской стороне. Для того что бы импортировать компонент только на клиенте, требуется зар
Дважды "что бы" - заменить на "чтобы"

"зарегистировать" очепятка

И еще, давай сделаем так
"Этот компонент используется для того, чтобы целенаправленно отрисовать его дочерний компонент только на клиентской стороне. Для того чтобы импортировать компонент только на клиенте, требуется зарегистрировать компонент в [плагинах, активных только на клиенте]"

2020-04-16 09:29 UTC, icehaunter commented on ru/api/components-client-only.md
> +> Этот компонент используется для того, что бы целенаправленно отрисовать его дочерний компонент только на клиентской стороне. Для того что бы импортировать компонент только на клиенте, требуется зар
Не очень понял часть про "сделаем так", не нашёл отличий от нынешней версии

2020-04-16 09:32 UTC, DreaMinder commented on ru/api/components-client-only.md
> +> Этот компонент используется для того, что бы целенаправленно отрисовать его дочерний компонент только на клиентской стороне. Для того что бы импортировать компонент только на клиенте, требуется зар
да, это я переносил свой коммент из gitlocalize, проморгал что ты уже внес правку "дочерний компонент". Т.е. нужно только исправить "что бы" в двух местах, в этом отличие.

2020-04-16 09:33 UTC, merged