RU: Translate modes_statically_generated.md
theartkod/docs pull request #50
Opened 2020-07-23 09:24 UTC by sp1r1don

2020-07-23 13:17 UTC, DreaMinder requested changes
Может есть еще что подправить, @icehaunter можешь посмотреть?

2020-07-23 13:17 UTC, DreaMinder commented on ru/homepage/modes_statically_generated.md
> +Генерация статических сайтов - очень горячая тема на сегодняшний день (aka JAMStack). Вместо того что бы сменить фреймворк и потратить время на его изучение, почему не убить двух зайцев одновременно?
```suggestion
Генерация статических сайтов (JAMStack) - очень горячая тема на сегодняшний день. Вместо того, чтобы сменить фреймворк и потратить время на его изучение, почему не убить двух зайцев одновременно?
```

2020-07-23 13:17 UTC, DreaMinder commented on ru/homepage/modes_statically_generated.md
> +предварительно обрабатывать все страницы и включать необходимый HTML. Также вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
```suggestion
предварительно обрабатывать все страницы и включать в них необходимый HTML. Также, вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
```

2020-07-24 09:23 UTC, icehaunter requested changes

2020-07-24 09:23 UTC, icehaunter commented on ru/homepage/modes_statically_generated.md
> +content_title: Статически сгенерированный
```suggestion
title: Статическая генерация
content_title: Статическая генерация
```

2020-07-24 09:23 UTC, icehaunter commented on ru/homepage/modes_statically_generated.md
> +Nuxt.js поддерживает генерацию статичного сайта основанного на вашем Vue приложении. Получаем идеальное сочетание
Тут, кажется, пропал перенос строки

2020-07-24 09:23 UTC, icehaunter commented on ru/homepage/modes_statically_generated.md
> +предварительно обрабатывать все страницы и включать необходимый HTML. Также вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
Тут пропущены запятые:

```suggestion
Nuxt.js поддерживает генерацию статичного сайта основанного на вашем Vue приложении. Получаем идеальное сочетание,
так как больше нет необходимости создавать сервер, но при этом есть возможность проводить SEO оптимизацию, т.к. Nuxt будет
предварительно обрабатывать все страницы и включать необходимый HTML. Также, вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
```

Но вообще мне не очень нравится настолько сложносочиненное предложение, особенно на главной.
```suggestion
Nuxt.js позволяет сгенерировать статичный сайт на основании вашего Vue-приложения. Получаем идеальное сочетание: вам больше не нужен сервер, однако будет работать SEO, так как Nuxt создаст все необходимые страницы заранее. Также, вы сможете без проблем опубликовать ваш проект на Netlify или GitHub pages.
```

2020-07-24 09:23 UTC, icehaunter commented on ru/homepage/modes_statically_generated.md
> +предварительно обрабатывать все страницы и включать необходимый HTML. Также вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
@DreaMinder, как ты считаешь?

2020-07-24 09:59 UTC, DreaMinder commented on ru/homepage/modes_statically_generated.md
> +Nuxt.js поддерживает генерацию статичного сайта основанного на вашем Vue приложении. Получаем идеальное сочетание
хм, не вижу такого...

2020-07-24 10:00 UTC, icehaunter commented on ru/homepage/modes_statically_generated.md
> +Nuxt.js поддерживает генерацию статичного сайта основанного на вашем Vue приложении. Получаем идеальное сочетание
Да, дифф неправильно прочитал, сори

2020-07-24 10:02 UTC, DreaMinder commented on ru/homepage/modes_statically_generated.md
> +предварительно обрабатывать все страницы и включать необходимый HTML. Также вы сможете без проблем публиковать ваш проект на Netlify или GitHub pages.
все таки закомитил этот последний вариант.

2020-07-24 10:02 UTC, DreaMinder approved these changes

2020-07-24 10:08 UTC, icehaunter approved these changes

2020-07-24 10:10 UTC, merged