RU: Translate modes_single_page_app.md
theartkod/docs pull request #51
Opened 2020-07-23 09:41 UTC by sp1r1don

2020-07-23 13:13 UTC, DreaMinder requested changes
Почти готово.

2020-07-23 13:13 UTC, DreaMinder commented on ru/homepage/modes_single_page_app.md
> +Не нужен SSR или статическая генерация, но всеже хотите пользоваться удобством разработки с Nuxt?
```suggestion
Не нужен SSR или статическая генерация, но все же хотите пользоваться удобством разработки с Nuxt?
```

2020-07-24 09:25 UTC, icehaunter commented on ru/homepage/modes_single_page_app.md
> +Вы переводите свое приложение на Nuxt и хотите начать с малого? Тогда SPA будет вашим лучшим выбором.
```suggestion
Вы переводите свое приложение на Nuxt и хотите начать с малого? Тогда SPA будет для вас лучшим выбором.
```

2020-07-24 10:03 UTC, DreaMinder approved these changes

2020-07-24 10:10 UTC, merged